# Generated by Django 2.1.2 on 2018-10-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181030_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[(1, '낮음'), (2, '보통'), (3, '높음')], default=2, max_length=1),
        ),
    ]
