# Generated by Django 2.1.2 on 2018-11-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[(1, '낮음'), (2, '보통'), (3, '높음')], default=2, max_length=3),
        ),
    ]
