# Generated by Django 2.1.2 on 2018-11-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20181101_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, '낮음'), (2, '보통'), (3, '높음')], default=2),
        ),
    ]
