# Generated by Django 2.1.2 on 2018-11-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20181101_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, '우선 순위 1'), (2, '우선 순위 2'), (3, '우선 순위 3')], default=1, verbose_name='우선 순위'),
        ),
    ]
